name: Contribution check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commit-message-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check commit message
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-body-regex: '(.*\n*)+(.*)'
  pr-content-check:
    runs-on: ubuntu-20.04
    steps:
    - name: Check PR content
      uses: bonitasoft/pr-diff-checker-action@1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        diffDoesNotContain: '["https://documentation.bonitasoft.com/", "Bonita BPM"]'
        extensionsToCheck: '[".adoc"]'
